'use client';
import {useEffect,useState} from 'react';

type ImageItem={id:string;name:string;placement:string;width:number;opacity:number;marginTop:number;marginBottom:number;enabled:boolean;src:string};
const placements=[['top','Верх сайта'],['aboveLeaderboard','Над таблицей'],['belowLeaderboard','Под таблицей'],['aboveRules','Над правилами'],['belowRules','Под правилами'],['footer','Над футером'],['background','Фоновое изображение'],['custom','Произвольное место']];

export default function Admin(){
 const [logged,setLogged]=useState(false),[password,setPassword]=useState(''),[images,setImages]=useState<ImageItem[]>([]),[file,setFile]=useState<File|null>(null),[name,setName]=useState('Новое изображение'),[placement,setPlacement]=useState('aboveLeaderboard'),[width,setWidth]=useState(100),[opacity,setOpacity]=useState(100),[marginTop,setMarginTop]=useState(0),[marginBottom,setMarginBottom]=useState(12),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const r=await fetch('/api/admin/images',{cache:'no-store'});if(r.status===401){setLogged(false);return}if(r.ok){setLogged(true);setImages(await r.json())}};
 useEffect(()=>{load()},[]);
 const login=async()=>{setBusy(true);const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password})});setBusy(false);if(r.ok){setPassword('');setLogged(true);load()}else setMessage('Неверный пароль')};
 const upload=async()=>{if(!file)return setMessage('Выбери изображение');if(file.size>6*1024*1024)return setMessage('Файл больше 6 МБ');setBusy(true);const reader=new FileReader();reader.onload=async()=>{const r=await fetch('/api/admin/images',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,placement,width,opacity,marginTop,marginBottom,src:reader.result})});const j=await r.json();setBusy(false);setMessage(r.ok?'Изображение добавлено':j.error||'Ошибка');if(r.ok){setFile(null);load()}};reader.readAsDataURL(file)};
 const patch=async(id:string,field:string,value:any)=>{await fetch('/api/admin/images',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,[field]:value})});load()};
 const remove=async(id:string)=>{if(!confirm('Удалить изображение?'))return;await fetch('/api/admin/images',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});load()};
 if(!logged)return <main style={styles.page}><div style={styles.login}><div style={styles.kicker}>MIDLANE ARENA</div><h1>ADMIN PANEL</h1><p>Закрытый раздел управления сайтом</p><input style={styles.input} type="password" placeholder="Пароль администратора" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()}/><button style={styles.button} onClick={login} disabled={busy}>{busy?'ПРОВЕРКА…':'ВОЙТИ'}</button>{message&&<div style={styles.error}>{message}</div>}</div></main>;
 return <main style={styles.page}><div style={styles.wrap}><div style={styles.head}><div><div style={styles.kicker}>MIDLANE ARENA</div><h1>ADMIN PANEL</h1><p>Управление изображениями сайта</p></div><button style={styles.darkButton} onClick={async()=>{await fetch('/api/admin/login',{method:'DELETE'});setLogged(false)}}>ВЫЙТИ</button></div>
 <section style={styles.card}><h2>Добавить изображение</h2><div style={styles.grid}><label>Название<input style={styles.input} value={name} onChange={e=>setName(e.target.value)}/></label><label>Расположение<select style={styles.input} value={placement} onChange={e=>setPlacement(e.target.value)}>{placements.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Ширина: {width}%<input type="range" min="10" max="100" value={width} onChange={e=>setWidth(+e.target.value)}/></label><label>Прозрачность: {opacity}%<input type="range" min="10" max="100" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label><label>Отступ сверху: {marginTop}px<input type="range" min="0" max="300" value={marginTop} onChange={e=>setMarginTop(+e.target.value)}/></label><label>Отступ снизу: {marginBottom}px<input type="range" min="0" max="300" value={marginBottom} onChange={e=>setMarginBottom(+e.target.value)}/></label></div><input style={styles.file} type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><button style={styles.button} onClick={upload} disabled={busy}>{busy?'ЗАГРУЗКА…':'＋ ДОБАВИТЬ НА САЙТ'}</button>{message&&<span style={styles.msg}>{message}</span>}</section>
 <section style={styles.card}><h2>Изображения на сайте</h2>{images.length===0?<p>Пока ничего не добавлено.</p>:images.map(img=><div key={img.id} style={styles.item}><img src={img.src} style={{...styles.preview,width:`${Math.min(img.width,45)}%`,opacity:img.opacity/100}}/><div style={styles.controls}><strong>{img.name}</strong><select style={styles.input} value={img.placement} onChange={e=>patch(img.id,'placement',e.target.value)}>{placements.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label>Ширина {img.width}%<input type="range" min="10" max="100" value={img.width} onChange={e=>patch(img.id,'width',+e.target.value)}/></label><label>Прозрачность {img.opacity}%<input type="range" min="10" max="100" value={img.opacity} onChange={e=>patch(img.id,'opacity',+e.target.value)}/></label><button style={img.enabled?styles.toggle:styles.off} onClick={()=>patch(img.id,'enabled',!img.enabled)}>{img.enabled?'● ВКЛЮЧЕНО':'○ ВЫКЛЮЧЕНО'}</button><button style={styles.delete} onClick={()=>remove(img.id)}>УДАЛИТЬ</button></div></div>)}</section></div></main>;
}
const styles:any={page:{minHeight:'100vh',background:'#060b12',color:'#e9f0f7',padding:'30px',fontFamily:'Arial,sans-serif'},wrap:{maxWidth:1100,margin:'0 auto'},login:{maxWidth:430,margin:'15vh auto',padding:36,background:'#0c1722',border:'1px solid #b99a52',borderRadius:14,textAlign:'center',boxShadow:'0 0 45px #000'},head:{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:25},kicker:{fontSize:11,letterSpacing:'.22em',color:'#b99a52'},h1:{margin:'8px 0',fontSize:34,letterSpacing:'.08em'},card:{background:'#0c1722',border:'1px solid #26394d',borderRadius:12,padding:22,marginBottom:18},h2:{marginTop:0},grid:{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:15},input:{width:'100%',boxSizing:'border-box',marginTop:7,padding:10,borderRadius:7,border:'1px solid #30465b',background:'#07111b',color:'#e9f0f7'},file:{margin:'18px 0',display:'block'},button:{padding:'11px 16px',border:0,borderRadius:7,background:'#b99a52',color:'#080b0f',fontWeight:900,cursor:'pointer'},darkButton:{padding:'9px 13px',border:'1px solid #35495d',borderRadius:7,background:'#0a121b',color:'#b8c6d3',cursor:'pointer'},error:{color:'#ff718b',marginTop:12},msg:{marginLeft:12,color:'#8fdcf5'},item:{display:'flex',gap:20,alignItems:'center',padding:'16px 0',borderTop:'1px solid #203244'},preview:{maxWidth:'45%',maxHeight:150,objectFit:'contain',background:'#050a10'},controls:{flex:1,display:'grid',gap:9},toggle:{padding:8,border:'1px solid #537b64',background:'#0b2118',color:'#83d5a3',borderRadius:6},off:{padding:8,border:'1px solid #596474',background:'#111922',color:'#738092',borderRadius:6},delete:{padding:8,border:'1px solid #713447',background:'#211018',color:'#ff829a',borderRadius:6}};
