'use client';
import {Fragment,useCallback,useEffect,useMemo,useState} from 'react';
import {RankIcon} from '@/app/components/rank-icon';

type HistoryPoint={lp:number;rank:string|null;position:number;recordedAt:string};

export default function RaceLive({slug}:{slug:string}){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[refreshMessage,setRefreshMessage]=useState(''),[expanded,setExpanded]=useState<string|null>(null),[now,setNow]=useState(Date.now());
 const load=useCallback(async()=>{try{const r=await fetch(`/api/races/${encodeURIComponent(slug)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ошибка загрузки');setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки')}finally{setLoading(false)}},[slug]);
 useEffect(()=>{load();const t=setInterval(load,60*60*1000);return()=>clearInterval(t)},[load]);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 const refresh=useCallback(async()=>{if(refreshing)return;setRefreshing(true);setRefreshMessage('Обновляем данные из OP.GG…');setError('');try{const r=await fetch(`/api/races/${encodeURIComponent(slug)}/refresh`,{method:'POST',cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ошибка обновления');await load();setRefreshMessage(j.failed?`Обновлено: ${j.updated}, ошибок: ${j.failed}`:`Обновлено игроков: ${j.updated}`);setTimeout(()=>setRefreshMessage(''),5000)}catch(e){setRefreshMessage('');setError(e instanceof Error?e.message:'Ошибка обновления')}finally{setRefreshing(false)}},[load,refreshing,slug]);
 const lastUpdate=useMemo(()=>data?.players?.reduce((d:any,p:any)=>!d||new Date(p.updatedAt)>new Date(d)?p.updatedAt:d,null),[data]);
 const countdown=useMemo(()=>{const end=new Date(new Date().getFullYear(),11,31,23,59,59,999);let s=Math.max(0,Math.floor((end.getTime()-now)/1000));const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);const sec=s%60;return `${d}д ${String(h).padStart(2,'0')}ч ${String(m).padStart(2,'0')}м ${String(sec).padStart(2,'0')}с`},[now]);
 const opggUrl=(riotId:string)=>{const [gameName,...tagParts]=String(riotId||'').split('#');const tagLine=tagParts.join('#');return `https://op.gg/lol/summoners/euw/${encodeURIComponent(gameName)}-${encodeURIComponent(tagLine)}`};
 const placeBadge=(position:number)=>position===1?'🏆':position===2?'🥈':position===3?'🥉':position;
 const historyFor=(riotId:string):HistoryPoint[]=>data?.history?.[riotId]||[];
 const positionDelta=(riotId:string,current:number)=>{const h=historyFor(riotId);if(h.length<2)return 0;const previous=h[h.length-2]?.position;return typeof previous==='number'?previous-current:0};
 const sparkline=(points:HistoryPoint[])=>{const values=points.length?points.map(x=>x.lp):[0];const min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min);return values.map((v,i)=>`${(i/Math.max(1,values.length-1))*100},${28-((v-min)/range)*24}`).join(' ')};
 const styles=`
 .leaderboardPage{position:relative;overflow:hidden}.leaderboardPage>*{position:relative;z-index:2}.mist{position:fixed;width:420px;height:160px;border-radius:50%;filter:blur(42px);opacity:.08;pointer-events:none;z-index:0!important}.mistA{left:-180px;top:38%;background:#56b9df;transform:rotate(-12deg)}.mistB{right:-170px;top:60%;background:#d54b69;transform:rotate(16deg)}.particles{position:fixed;inset:0;pointer-events:none;z-index:0!important;opacity:.3;background-image:radial-gradient(circle,#b7e7f6 0 1px,transparent 1.5px),radial-gradient(circle,#e6c778 0 1px,transparent 1.5px);background-size:180px 210px,260px 280px;background-position:20px 40px,120px 80px;animation:drift 18s linear infinite}.stats>div{transition:.2s}.stats>div:hover{border-color:#35546a;transform:translateY(-1px)}.tableWrap{overflow-x:auto}table{min-width:930px}tbody>tr:not(.detailsRow){cursor:pointer;transition:background .18s}tbody>tr:not(.detailsRow):hover{background:#10202d99}.positionDelta{display:inline-block;margin-left:4px;font-size:8px;vertical-align:middle}.positionDelta.up{color:#64d39a}.positionDelta.down{color:#e57a86}.gameProgress{width:50px;height:2px;margin-top:4px;background:#152331;border-radius:99px;overflow:hidden}.gameProgress i{display:block;height:100%;background:#4b9dbb;border-radius:99px}.expandCell{width:24px;text-align:center;color:#6e8397;font-size:17px}.detailsRow td{padding:0;background:#07101a;border-bottom:1px solid #253448}.playerDetails{padding:13px 15px;border-left:2px solid #347f9f;background:linear-gradient(90deg,#0d1c29,#081019)}.detailHead{display:flex;justify-content:space-between;gap:10px;align-items:center}.detailHead b{font-size:12px}.detailHead span{margin-left:8px;color:#70869a;font-size:9px}.freshness{font-size:8px;color:#6c8a82}.detailGrid{display:grid;grid-template-columns:repeat(6,1fr) 2fr;gap:6px;margin-top:10px}.detailStat{padding:8px;border:1px solid #1f3040;border-radius:7px;background:#0a1520}.detailStat span{display:block;font-size:7px;letter-spacing:.1em;color:#688096}.detailStat strong{display:block;margin-top:4px;font-size:14px}.lpChart{padding:7px 9px;border:1px solid #1f3040;border-radius:7px;background:#0a1520;min-width:140px}.lpChart>div{display:flex;justify-content:space-between;gap:8px;font-size:7px;letter-spacing:.08em;color:#71879a}.lpChart b{font-weight:600;letter-spacing:0;color:#9db5c6}.lpChart svg{width:100%;height:34px;margin-top:4px;color:#67c8e8}.refreshMessage{display:flex;gap:8px;align-items:center}.refreshMessage.isRefreshing span{animation:spin 1s linear infinite}.updateLine{text-align:center;color:#536a7d;font-size:8px;letter-spacing:.05em;padding:11px 0 0}@keyframes spin{to{transform:rotate(360deg)}}@keyframes drift{from{transform:translate3d(0,0,0)}50%{transform:translate3d(20px,-10px,0)}to{transform:translate3d(0,0,0)}}
 @media(max-width:760px){.stats{grid-template-columns:repeat(2,1fr)}.stats>div{padding:9px 10px}.stats b{font-size:12px}.tableTitle{align-items:flex-start;gap:8px}.refreshButton{font-size:8px;padding:6px 8px}.detailHead{align-items:flex-start;flex-direction:column}.detailGrid{grid-template-columns:repeat(2,1fr)}.lpChart{grid-column:span 2}.updateLine{font-size:7px}}
 `;
 return <main className="wrap leaderboardPage">
  <style jsx global>{styles}</style>
  <div className="mist mistA"/><div className="mist mistB"/><div className="particles" aria-hidden="true"/>
  {loading&&!data?<div className="card">Загрузка leaderboard…</div>:error?<div className="card error">{error}</div>:<>
   <header className="leaderboardHeader heroHeader">
    <div className="inkBlade inkBladeLeft" aria-hidden="true"/><div className="inkBlade inkBladeRight" aria-hidden="true"/>
    <div className="spiritOrb spiritOrbBlue" aria-hidden="true"/><div className="spiritOrb spiritOrbRed" aria-hidden="true"/>
    <div className="heroTitle"><div className="eyebrow">LEAGUE OF LEGENDS · EUW</div><h1>Midlane Arena</h1><div className="heroDivider"><i/><span>✦</span><i/></div><p className="muted">PRIME RACE · RANKED SOLO/DUO</p></div>
   </header>
   <section className="raceOverview">
    <div className="stats"><div><span>Участники</span><b>{data.players.length}</b></div><div><span>Лидер</span><b>{data.players[0]?`${data.players[0].rank} · ${data.players[0].lp} LP`:'—'}</b></div><div><span>До конца</span><b>{countdown}</b></div></div>
   </section>
   <div className="raceContent">
    <section className="card tableCard">
     <div className="tableTitle"><div><b>LEADERBOARD</b><span className="muted leaderboardSub">RANKED SOLO/DUO</span></div><div className="tableActions"><span className="muted">по рангу и LP</span><button className="refreshButton" onClick={refresh} disabled={refreshing}>{refreshing?'⟳ ОБНОВЛЕНИЕ…':'⟳ ОБНОВИТЬ ДАННЫЕ'}</button></div></div>
     {refreshMessage&&<div className={`refreshMessage ${refreshing?'isRefreshing':''}`}><span>✦</span>{refreshMessage}</div>}
     <div className="tableWrap"><table><thead><tr><th>#</th><th>Игрок</th><th>Ранг</th><th>LP</th><th>W/L</th><th>Матчи</th><th>WR</th><th>LP/игра</th><th>Peak</th><th/></tr></thead><tbody>{data.players.map((p:any)=><Fragment key={p.riotId}>
      <tr className={p.position<=3?`topRow prize-${p.position}`:''} onClick={()=>setExpanded(expanded===p.riotId?null:p.riotId)}>
       <td className="pos">{placeBadge(p.position)}{positionDelta(p.riotId,p.position)!==0&&<span className={`positionDelta ${positionDelta(p.riotId,p.position)>0?'up':'down'}`}>{positionDelta(p.riotId,p.position)>0?'▲':'▼'} {Math.abs(positionDelta(p.riotId,p.position))}</span>}</td>
       <td><a className="playerLink" href={opggUrl(p.riotId)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{p.riotId}</a><small>{p.region}</small></td>
       <td><div className="rankCell"><RankIcon rank={p.rank} size={96}/><span>{p.rank}</span></div></td><td><strong>{p.lp}</strong></td><td>{p.wins} / {p.losses}</td><td><strong>{p.totalMatches}</strong><div className="gameProgress"><i style={{width:`${Math.min(100,p.totalMatches/3)}%`}}/></div></td><td>{p.winrate}%</td><td>{p.lpPerGame}</td><td>{p.peakLp}</td><td className="expandCell">{expanded===p.riotId?'⌃':'⌄'}</td>
      </tr>
      {expanded===p.riotId&&<tr className="detailsRow"><td colSpan={10}><div className="playerDetails"><div className="detailHead"><div><b>{p.riotId}</b><span>{p.rank} · {p.lp} LP</span></div><div className="freshness">обновлено {new Date(p.updatedAt).toLocaleString('ru-RU')}</div></div><div className="detailGrid"><div className="detailStat"><span>ПОБЕДЫ</span><strong>{p.wins}</strong></div><div className="detailStat"><span>ПОРАЖЕНИЯ</span><strong>{p.losses}</strong></div><div className="detailStat"><span>ВИНРЕЙТ</span><strong>{p.winrate}%</strong></div><div className="detailStat"><span>МАТЧИ</span><strong>{p.totalMatches}</strong></div><div className="detailStat"><span>LP / ИГРА</span><strong>{p.lpPerGame}</strong></div><div className="detailStat"><span>PEAK LP</span><strong>{p.peakLp}</strong></div><div className="lpChart"><div><span>ИСТОРИЯ LP</span><b>{historyFor(p.riotId).length} точек</b></div><svg viewBox="0 0 100 30" preserveAspectRatio="none"><polyline fill="none" stroke="currentColor" strokeWidth="1.6" points={sparkline(historyFor(p.riotId))}/></svg></div></div></div></td></tr>}
     </Fragment>)}</tbody></table></div>
    </section>
    <aside className="card raceRules"><div className="rulesEyebrow">MIDLANE ARENA</div><h2>ПРАВИЛА УЧАСТИЯ</h2><div className="rulesDivider"><i/><span>✦</span><i/></div><div className="rulePrize"><span>ПРИЗОВОЙ ФОНД</span><strong>50.000 ₽</strong></div><ul><li><b>Лимит игр</b><span>300</span></li><li><b>Формат</b><span>Никакого дуо</span></li><li><b>Победитель</b><span>Участник, находящийся на самом верху таблицы в конце сезона</span></li></ul><div className="rulesNote"><b>P.S.</b> Делайте клипы своих удачных / крутых моментов, если хотите попасть в видеомонтаж от <strong>Hazakuro</strong></div></aside>
   </div>
   <div className="updateLine">{lastUpdate?`Данные обновлены: ${new Date(lastUpdate).toLocaleString('ru-RU')}`:'Данные ещё не обновлялись'}</div>
   <footer className="siteFooter">Сделано благодаря упорному труду <strong>Hazakuro</strong></footer>
  </>}
 </main>
}
